apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-creator-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: route-creator
  template:
    metadata:
      labels:
        app: route-creator
    spec:
      containers:
      - name: route-creator-cnt
        image: luciantin/node-server:1.0.0
        ports:
        - containerPort: 5000
