apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu-debug
  name: ubuntu-debug
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-debug
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu-debug
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command: ["/bin/sleep", "3650d"]
        resources: {}